services:
  remark42:
    environment:
      REMARK_URL: "https://comments.laxarchive.org"
      ALLOWED_HOSTS: "'self',https://comments.laxarchive.org,https://remark42-3-74-72-66.nip.io,https://laxarchive.org,https://www.laxarchive.org,http://localhost:3000,http://127.0.0.1:3000"
